CREATE OR REPLACE PROCEDURE STP_CTLDEVOL_UNIKA (
  P_TIPOEVENTO INT,
  P_IDSESSAO   VARCHAR2,
  P_CODUSU     INT
) AS
  BEFORE_INSERT INT := 0;
  BEFORE_UPDATE INT := 4;
  vStatusUso VARCHAR2(1);
  vDataFin   DATE;
BEGIN
  IF P_TIPOEVENTO IN (BEFORE_INSERT, BEFORE_UPDATE) THEN
    vStatusUso := NVL(SANKHYA.EVP_GET_CAMPO_TEXTO(P_IDSESSAO, 'STATUSUSO'), ' ');
    vDataFin   := SANKHYA.EVP_GET_CAMPO_DTA(P_IDSESSAO, 'DATAFIN');

    IF vStatusUso = 'D' AND vDataFin IS NULL THEN
      RAISE_APPLICATION_ERROR(-20001, 'Informe Data Final no formulário.');
    END IF;
  END IF;
END;